# Generated by Django 3.1.5 on 2021-01-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournoiSport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPhase', models.IntegerField()),
                ('typePhase', models.CharField(max_length=50)),
                ('nbTeamPerPool', models.IntegerField()),
                ('nbTeamQualified', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPool', models.IntegerField()),
            ],
        ),
    ]
