# Generated by Django 3.1.5 on 2021-01-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournoiSport', '0002_phase_pool'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='equipe',
            new_name='team',
        ),
    ]
