# Generated by Django 3.1.5 on 2021-01-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournoiSport', '0004_team_idpoolt'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='idTeam',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
