# Generated by Django 3.1.5 on 2021-01-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournoiSport', '0006_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='tournament',
            name='nb',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='tournament',
            name='place',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sport',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
