# Generated by Django 3.1.5 on 2021-01-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournoiSport', '0007_auto_20210121_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='date',
        ),
    ]
