# Generated by Django 3.1.5 on 2021-01-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournoiSport', '0008_remove_tournament_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tournament',
        ),
    ]
